plugins {
	id 'base'
	id 'groovy'
	id 'idea'
	id 'java-library'
}

version = '0.4-SNAPSHOT'
group = "net.ijus"

repositories {
	mavenLocal()
    mavenCentral()
}

dependencies {
	implementation libs.slf4j
	implementation libs.jetbrains.annotations
	implementation libs.snakeyaml.engine
	testImplementation libs.spock.core, { exclude module: 'groovy' }
	testImplementation libs.mockito
	testRuntimeOnly libs.bytebuddy
}
