plugins {
	id 'base'
	id 'groovy'
	id 'idea'
	id 'java-library'
}

version = '1.0.0'
group = "com.trccompanies"

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

repositories {
	mavenLocal()
    mavenCentral()
}

dependencies {
	implementation libs.bundles.groovy
	implementation libs.slf4j
	implementation libs.jetbrains.annotations
	implementation libs.snakeyaml.engine
	testImplementation libs.spock.core
	testImplementation libs.mockito
	testRuntimeOnly libs.bytebuddy
}
